dead_man_switch_button: 4 #is button marked with a 1 on warthog controller

axis_linear: 4  # Right thumb stick vertical
scale_linear: 0.0015 # tracks
#scale_linear: 0.0007896 # For Olivier experiment, to drive at 0.5 m/s on tracks
scale_linear_turbo: -0.0038

axis_angular: 3  # Right thumb stick horizontal
scale_angular: -0.0015
scale_angular_turbo: -0.0038

#axis_linear: 4  # Right thumb stick vertical
#scale_linear: 0.7
#scale_linear_turbo: 1.5
#
#axis_angular: 3  # Right thumb stick horizontal
#scale_angular: 0.3
#scale_linear_turbo: 1.0

enable_button: 5  # Right trigger button
enable_turbo_button: 2  # Left trigger button

expo_coeff: 3 # Exponential curve coefficient
base_width: 1.1652 # normal is 1.1652 and refers to the center of wheel left to center of wheel right. Modify this value to change the turning speed, differs depending on terrain type.
enable_track_control_button: 6 #button 6 is marked by a "3" on the warthog controller
deadzone: 100 # on the controller the inputs are from -1023 to 1023, so 100 is 1/10 of total value 
