axis_linear: 4  # Left thumb stick vertical
scale_linear: 0.0007
scale_linear_turbo: 0.003

axis_angular: 3  # Left thumb stick horizontal
scale_angular: -0.0007
scale_angular_turbo: -0.003

#axis_linear: 4  # Left thumb stick vertical
#scale_linear: 0.7
#scale_linear_turbo: 1.5
#
#axis_angular: 3  # Left thumb stick horizontal
#scale_angular: 0.3
#scale_linear_turbo: 1.0

enable_button: 5  # Left trigger button
enable_turbo_button: 2  # Right trigger button

expo_coeff: 2 # Exponential curve coefficient